#!/bin/bash
git clone https://github.com/EmmaGerrits/project_pbfb



git clone https://github.com/AMVeenstraSkirl/Project-PBfB2018



git clone https://github.com/sorshapassmore/PBfB_Personal_Project.git



git clone https://github.com/s3465535/DNA-phylogenetic-trees/



git clone https://github.com/GiuliaLeone/G.Leone_F.Carey_Final_Project



git clone https://github.com/Laura0607/PBfB2018



git clone https://github.com/TesselLagerwerf/BioInformaticsProject



git clone https://github.com/CharleyyRussell/Genetic_Sequence_Matching_Cetaceans



git clone https://github.com/pbrinker/Match-tra-haplotypes



git clone https://github.com/erikvanhaeringen/plasmidproject.git



git clone https://github.com/sebmader/Coevolution_phylo_bioinformatics2018



git clone https://github.com/madhurya333/Amaury_Madhurya_Project.git



git clone https://github.com/Donne96/PBfB_Pop_structure



git clone https://github.com/LauraStaal/PBFB2018_Project
