#!/bin/bash

function show_grade {
  n_points=$1
  echo "n_points: "$n_points
  if [[ n_points < 1 ]]; then $n_points=$((n_points+1)); fi
  echo "n_points (after correcting for minumum): "$n_points
  echo "Grade: "$n_points
}

n_points=0

if [[ ! -f grade_me.txt ]] ; 
then
  echo "File 'grade_me.txt' not found" 
  show_grade $n_points
  exit
fi

# Username is in the first line, after a whitespace
username=`cat grade_me.txt | head -n 1 | tail -n 1 | cut -d " " -f 1`

# Reponame is in the first line, after a whitespace
reponame=`cat grade_me.txt | head -n 2 | tail -n 1 | cut -d " " -f 2`

echo "Username: "$username
echo "Reponame: "$reponame
