#!/bin/bash

source ./functions

test_get_grade_no_grade_me()
{
  assertEquals 1 `get_grade absent_file.txt`
}

test_get_grade_fail_all()
{
  echo "username: absent" > fail_all.txt
  echo "reponame: absent_too" >> fail_all.txt
  assertEquals 1 `get_grade fail_all.txt`
}

test_pass_build_passes()
{
  # richelbilderbeek/correct_cpp passes
  assertEquals 1 `pass_build richelbilderbeek correct_cpp`
}

test_pass_build_fails()
{
  # richelbilderbeek/correct_cpp_scoreboard passes fails
  assertEquals 0 `pass_build richelbilderbeek correct_cpp_scoreboard`
}

# load shunit2
. ../shunit2/shunit2